{
  "uuid": "cd13db1c-30d9-4e64-adbc-05a2c06003f1",
  "historyId": "8d01dbaa0e9232991935bce6499af440",
  "testCaseId": "a9586c33faab3e5b9504a84d6f3125c2",
  "fullName": "AcademicNet.Tests:StudentServiceTests.GetRanking_perStudent_Deve_Lancar_ArgumentException_Se_Filtros_Invalidos()",
  "labels": [
    {
      "name": "thread",
      "value": ".NET Long Running Task"
    },
    {
      "name": "host",
      "value": "DESKTOP-RI3P2DJ"
    },
    {
      "name": "language",
      "value": "C#"
    },
    {
      "name": "framework",
      "value": "xUnit.net"
    },
    {
      "name": "testClass",
      "value": "StudentServiceTests"
    },
    {
      "name": "testMethod",
      "value": "StudentServiceTests.GetRanking_perStudent_Deve_Lancar_ArgumentException_Se_Filtros_Invalidos"
    },
    {
      "name": "package",
      "value": "StudentServiceTests"
    }
  ],
  "links": [],
  "name": "StudentServiceTests.GetRanking_perStudent_Deve_Lancar_ArgumentException_Se_Filtros_Invalidos",
  "status": "failed",
  "statusDetails": {
    "known": false,
    "muted": false,
    "flaky": false,
    "message": "Assert.Throws() Failure: No exception was thrown\r\nExpected: typeof(System.ArgumentException)",
    "trace": "   at Xunit.Assert.Throws(Type exceptionType, Exception exception) in /_/src/xunit.assert/Asserts/ExceptionAsserts.cs:line 34\r\n   at Xunit.Assert.ThrowsAsync[T](Func`1 testCode) in /_/src/xunit.assert/Asserts/ExceptionAsserts.cs:line 340\r\n   at StudentServiceTests.GetRanking_perStudent_Deve_Lancar_ArgumentException_Se_Filtros_Invalidos() in C:\\Users\\pablo\\OneDrive\\√Årea de Trabalho\\POO-DEV\\AcademicNetAPI\\AcademicNet.Tests\\StudentServiceTests.cs:line 65\r\n   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 276\r\n--- End of stack trace from previous location ---\r\n   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48\r\n   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90"
  },
  "stage": "finished",
  "steps": [],
  "attachments": [],
  "parameters": [],
  "start": 1750200031780,
  "stop": 1750200031847
}